version: '3.8'

services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: movie
    ports:
      - 3306:3306
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql

  web:
    build:
        context: .
    command: npm start
    volumes:
        - .:/app/
        - /app/node_modules
    ports:
        - 3000:3000
    depends_on:
        - mysqldb
    environment:
        MYSQL_HOST: mysqldb
volumes:
  db-config:
  db-data: